version: '3.8'

services: 
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mdptrocool
      MYSQL_DATABASE: uber_eats
    ports:
      - 3307:3306
    volumes: 
      - .mysql_data/:/data_host/data
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: api
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    
  mongo:
    image: mongo
    ports:
      - "27020:27017"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mdptrocool
    volumes:
      - .mongo_data/:/data_host/data

networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
 